# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Automaatio- ja systeemitekniikan kilta
email: hallitus@as.fi
description: Aivan Sama!
url: "https://as.fi" # the base hostname & protocol for your site
baseurl: ''
permalink: /uutiset/:year/:month/:day/:title.html # DO NOT CHANGE!

# Build settings
markdown: kramdown

# Exclude project files from build
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

lang: fi

plugins:
  - jekyll-archives

jekyll-archives:
  enabled: ['year', 'month', 'day', 'categories']
  layouts:
    year: archive-year
    month: archive-month
    day: archive-day
    category: archive-category
  permalinks:
    year: /uutiset/:year/ # DO NOT CHANGE!
    month: /uutiset/:year/:month/ # DO NOT CHANGE!
    day: /uutiset/:year/:month/:day/ # DO NOT CHANGE!
    category: /uutiset/kategoria/:name/ # DO NOT CHANGE!
