version: "2"
services:
    jekyllbuild:
        build:
            context: "."
            dockerfile: "jekyll.docker"
            args:
                - COMMIT_HASH=${COMMIT_HASH}
        volumes_from:
            - nginx

    nginx:
        build:
            context: "."
            dockerfile: "nginx.docker"
        ports:
            - "8080:80"
        volumes:
            - /usr/share/nginx/html
